### ISSUE TITLE
Why is LIBSVM superior? (May I ask a slightly off-topic question here?)

### ISSUE THREAD

**Issue by WuSiren** [JuliaML/LIBSVM.jl#104]
I am very curious why `LIBSVM` is superior (isn't it? ). Since a general SVM problem is usually a quadratic program or semi-definite program, if I solve it using some other efficient general-purpose quadratic or semi-definite program solvers, will higher performance than `LIBSVM`  be achieved? In other words, I wonder what more work `LIBSVM` does at the technical level than other QP/SDP solvers? (No offense, I've always been a big fan of `LIBSVM`.)

Thank you in advance!

**Comment by barucden** [comment]
As I understand it, LIBSVM (the C++ library that this package calls) implements a few solvers that specifically target the SVM problems. I'd expect that a specific solver has *some* benefits over a general one, but I know almost nothing about the solvers.

Nevertheless, I am closing this issue because it is not really an issue. Please, create a topic at [Discourse](https://discourse.julialang.org/) if you want to discuss your question with the julia community, or contact the original author at https://github.com/cjlin1/libsvm.
